### ISSUE TITLE
Allow submitting applications through web app

### ISSUE THREAD

**Issue by gptbrooke** [vibecamp/vibecamp-web#4]
Slightly higher priority than calendar; unless it's very difficult to implement.

We would like a way to allow people to submit an application to purchase tickets (with no referral codes granted). Ideally, filling out the application puts them in the DB, and their step in the process reflects on their account (something like: application under review, application accepted, application denied). We can help with copy both for application Qs and for the process steps.

If that's too much coding overhead, happy to compromise for now & put a link to a google form somewhere!

**Comment by ColbyWhitted** [comment]
We have already created a model application form in Google forms. Below is the empty and exported google sheet that shows all the fields.

[Vibeclipse Application Form (Responses) - Form Responses 1.csv](https://github.com/vibecamp/vibecamp-web/files/13589413/Vibeclipse.Application.Form.Responses.-.Form.Responses.1.csv)
